### ISSUE TITLE
[Edgware.RELEASE]Hystrix Dashboard Cannot display anything for Turbine Stream

### ISSUE THREAD

**Issue by eacdy** [spring-cloud/spring-cloud-netflix#2475]
I update my samples to Edgware.RELEASE  then I find that Hystrix Dashboard Cannot display anything for Turbine Stream.

Turbine Stream：<http://localhost:8989> , When I call it, I Can get data like below:

```json
data: {"rollingCountFallbackFailure":0,"rollingCountFallbackSuccess":0,"propertyValue_circuitBreakerRequestVolumeThreshold":"20","propertyValue_circuitBreakerForceOpen":false,"propertyValue_metricsRollingStatisticalWindowInMilliseconds":"10000","latencyTotal_mean":0,"type":"HystrixCommand","rollingCountResponsesFromCache":0,"TypeAndName":"TypeAndName=>HystrixCommand_zuul-server.microservice-provider-user","rollingCountTimeout":0,"propertyValue_executionIsolationStrategy":"SEMAPHORE","instanceId":"zuul-server:-3102666220667402369","rollingCountFailure":0,"rollingCountExceptionsThrown":0,"latencyExecute_mean":0,"isCircuitBreakerOpen":false,"errorCount":0,"group":"RibbonCommand","rollingCountSemaphoreRejected":0,"latencyTotal":{"0":0,"25":0,"50":0,"75":0,"90":0,"95":0,"99":0,"99.5":0,"100":0},"requestCount":0,"rollingCountCollapsedRequests":0,"rollingCountShortCircuited":0,"latencyExecute":{"0":0,"25":0,"50":0,"75":0,"90":0,"95":0,"99":0,"99.5":0,"100":0},"propertyValue_circuitBreakerSleepWindowInMilliseconds":"5000","currentConcurrentExecutionCount":0,"propertyValue_executionIsolationSemaphoreMaxConcurrentRequests":"100","errorPercentage":0,"rollingCountThreadPoolRejected":0,"propertyValue_circuitBreakerEnabled":true,"propertyValue_executionIsolationThreadInterruptOnTimeout":true,"propertyValue_requestCacheEnabled":true,"rollingCountFallbackRejection":0,"propertyValue_requestLogEnabled":true,"rollingCountSuccess":0,"propertyValue_fallbackIsolationSemaphoreMaxConcurrentRequests":"10","InstanceKey":"InstanceKey=>zuul-server:-3102666220667402369","propertyValue_circuitBreakerErrorThresholdPercentage":"50","propertyValue_circuitBreakerForceClosed":false,"name":"zuul-server.microservice-provider-user","reportingHosts":1,"propertyValue_executionIsolationThreadPoolKeyOverride":"null","propertyValue_executionIsolationThreadTimeoutInMilliseconds":"2000"}
```

But When I put this URL into Hystrix Dashboard, I Will never get the graph!
<img width="1277" alt="hystrix-dashboard" src="https://user-images.githubusercontent.com/9031050/33309345-cd42db6c-d458-11e7-8794-ae0a002b1009.png">

Then I downgrade my Code to `Dalston.SR4` , everything works! I think it's a Turbine Server bug of `Edgware.RELEASE` .

CODE IS HERE: <https://gitee.com/itmuch/spring-cloud-yes> . Hope you Can help me.

@ryanjbaxter @dsyer @royclarkson

**Comment by daniellavoie** [comment]
We came to the same issue with our forked code. So I had to fix this issue. the problem comes from the Netty upgrade. We need to define a `message` `EventType` when creating an `ServerEventType`. 

I had to fix that issue on Spring Cloud Services. I'll try to submit a fix for OSS.

https://github.com/spring-cloud/spring-cloud-netflix/blob/6c65266f052777159d8df320adb638805e31d810/spring-cloud-netflix-turbine-stream/src/main/java/org/springframework/cloud/netflix/turbine/stream/TurbineStreamConfiguration.java#L105

**Comment by spencergibb** [comment]
Thanks @daniellavoie looking forward to it.

**Comment by eacdy** [comment]
@daniellavoie Bingo. I also locate the error in `TurbineStreamConfiguration` ,but I don't know much about SSE.

**Comment by ryanjbaxter** [comment]
Fixed in #2484

**Comment by YorkWong** [comment]
Although I’ve used the codes of ver. 1.4.1, the Dashboard still cannot display the graphs normally;However, when I add a line break `\n`  (as shown below) in the codes, the Dashboard can display normally.

```java
.flatMap(data -> response.writeAndFlush(new ServerSentEvent(
                        null,
                        Unpooled.copiedBuffer("message",
                            StandardCharsets.UTF_8),
                        Unpooled.copiedBuffer(JsonUtility.mapToJson(data) + "\n",
                            StandardCharsets.UTF_8))));
```
or
```java
.flatMap(data -> response.writeAndFlush(new ServerSentEvent(
                        null,
                        Unpooled.copiedBuffer("message"+ "\n",
                            StandardCharsets.UTF_8),
                        Unpooled.copiedBuffer(JsonUtility.mapToJson(data),
                            StandardCharsets.UTF_8))));
```

**Comment by ryanjbaxter** [comment]
If you believe there is a bug please open another issue

cc: @daniellavoie

**Comment by eacdy** [comment]
@ryanjbaxter After I upgrate my verson to Edgware.SR1, the problem is still .

**Comment by spencergibb** [comment]
@eacdy this fix will be part of Edgware.SR2

**Comment by Taifone-Geek** [comment]
Hello

I have probably the same problem in my case i'm trying to access in my stream but the navigator load data in didn't display them any help
