### ISSUE TITLE
Allow streaming of multipart requests/response in Zuul proxy

### ISSUE THREAD

**Issue by amitabhprasad** [spring-cloud/spring-cloud-netflix#2773]
When calling the service directly, the download streams fine, however when calling through Zuul it seems to download the file to zuul first and then stream it from there. 
This become an issue for large file downloads especially when running in GB's, file download starts only after entire file is read in Zuul filter, this frces us to use really large heap size and other performance issues.
We debugged the code and looks like problem happens  during

> private void writeResponse(InputStream zin, OutputStream out) throws Exception {
		byte[] bytes = buffers.get();
		int bytesRead = -1;
		while ((bytesRead = zin.read(bytes)) != -1) {
			out.write(bytes, 0, bytesRead);
		}
	}
in org.springframework.cloud.netflix.zuul.filters.post.SendResponseFilter

That loops over untill entire file is read. I tried sending the request as /zuul/...
but nothing helped, please let me know if there is a way out ? we are totally stuck.

**Comment by amitabhprasad** [comment]
We are using "Dalston.SR2" release.

**Comment by spencergibb** [comment]
I'd say zuul isn't built for multi GB file upload or downloads.

**Comment by amitabhprasad** [comment]
@spencergibb 
Isn't it is used for streaming videos etc. in netflix ? right now most of our files are smaller but in certain case it does run into a gig or more.

**Comment by spencergibb** [comment]
No, streaming bits do not go thru zuul.

**Comment by amitabhprasad** [comment]
Is there any wayout to overcome this limitation ?

**Comment by amitabhprasad** [comment]
@spencergibb 
It's not the problem of GB of download but what if 100's of user trying to download 10 MB or so  of data ?

**Comment by spencergibb** [comment]
What are you expecting that code to do? It doesn't read the whole file into memory.

**Comment by amitabhprasad** [comment]
Problem is it doesn't start streaming untill it has read entire file in memory.
I am not sure if we are missing anything from our side.
Sample code from our service, let me know if we are missing anything

> String fullPath = "\documents\data\testfile.mp4";
			Enumeration<String> headerNames = request.getHeaderNames();
			while(headerNames.hasMoreElements()){
				String element = headerNames.nextElement();
				String value =  request.getHeader(element);
				System.out.println("element = "+element+" value = "+value);
			}
			File downloadFile = new File(fullPath);
	        FileInputStream inputStream = new FileInputStream(downloadFile);
	        InputStreamResource inputStreamResource = new InputStreamResource(inputStream);
	        HttpHeaders headers = new HttpHeaders();
	        headers.setContentLength(downloadFile.length());
	        ServletContext context = request.getServletContext();
	        // get MIME type of the file
	           String mimeType = context.getMimeType(fullPath);
	           if (mimeType == null) {
	               // set to binary type if MIME mapping not found
	               mimeType = "application/octet-stream";
	           }
	           System.out.println("MIME type: " + mimeType);
	           
	        // set content attributes for the response
	           response.setContentType(mimeType);
	           response.setContentLength((int) downloadFile.length());
	           
	        return new ResponseEntity<InputStreamResource>(inputStreamResource, headers, HttpStatus.OK);

**Comment by spencergibb** [comment]
The code you pointed to in your first comment doesn't read the file to memory.

**Comment by amitabhprasad** [comment]
This is the code for file download from my service layer, but when it passes through Zuul, teh response Zuul filter kicks in and get stuck at the code mentioned above in class "SendResponseFilter".
This works fine If I do direct download bypassing Zuul.

**Comment by sta-szek** [comment]
@spencergibb so it means that zuul does not read file to memory at all? Instead of it redirects stream to another stream?

**Comment by aivans** [comment]
The download/upload of big files via the ZuulServlet used to work smoothly. No DispatcherServlet involved.
We are performing an upgrade these days and we noticed it is not working anymore.

Will investigate.

**Comment by ryanjbaxter** [comment]
@aivans this should be fixed in Edgware.SR5.

**Comment by richard-yao** [comment]
@ryanjbaxter this bug still exist in Finchley.RELEASE, when I try to upload file with 111MB size and the zuul gateway application with max heap size in 64MB, the file upload will failed and throws OOM, can you ensure this issue fixed in which one release？ For now, the latest release is Finchley SR2.

**Comment by ryanjbaxter** [comment]
@richard-yao I was referring to the issue specifically pointed out by @aivans' comment (https://github.com/spring-cloud/spring-cloud-netflix/issues/2773#issuecomment-432973112).  This issue (2773) has not been addressed.

**Comment by spencergibb** [comment]
This module has entered [maintenance mode](https://github.com/spring-cloud/spring-cloud-netflix#modules-in-maintenance-mode). This means that the Spring Cloud team will no longer be adding new features to the module. We will fix blocker bugs and security issues, and we will also consider and review small pull requests from the community.

**Comment by ryanjbaxter** [comment]
It is not that is was working, we are just not going to add any new features at this point to support it
